name: admetMesh-Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '10,40 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.13.0'
    - name: Install dependencies
      run: npm ci
    - name: Update Result
      run: node scripts/index.js > data/result/meshRes.csv
    - name: Update Readme
      run: node scripts/time.js > README.md
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am ":robot: update meshRes.csv automatically"
          git pull
          git push
